In [ ]:
import numpy as np
import pandas as pd
height = [120,122,127,143,148,131,163,185,192,156,177,189,139,184,186]
bins = [118, 125, 135, 160, 200]
category=pd.cut(height,bins)
category

[(118, 125], (118, 125], (125, 135], (135, 160], (135, 160], ..., (160, 200], (160, 200], (135, 160], (160, 200], (160, 200]]
Length: 15
Categories (4, interval[int64, right]): [(118, 125] < (125, 135] < (135, 160] < (160, 200]]

In [ ]:
pd.value_counts(category)

/tmp/ipykernel_729/1463743115.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(category)

(160, 200]    7
(135, 160]    4
(125, 135]    2
(118, 125]    2
Name: count, dtype: int64

In [ ]:
bin_names = ['Short Height', 'Average height', 'Good Height', 'Taller']
pd.cut(height, bins, labels=bin_names)

['Short Height', 'Short Height', 'Average height', 'Good Height', 'Good Height', ..., 'Taller', 'Taller', 'Good Height', 'Taller', 'Taller']
Length: 15
Categories (4, object): ['Short Height' < 'Average height' < 'Good Height' < 'Taller']

In [ ]:
pd.cut(np.random.rand(40), 5, precision=2)

[(0.61, 0.8], (0.61, 0.8], (0.61, 0.8], (0.24, 0.43], (0.43, 0.61], ..., (0.61, 0.8], (0.43, 0.61], (0.048, 0.24], (0.43, 0.61], (0.24, 0.43]]
Length: 40
Categories (5, interval[float64, right]): [(0.048, 0.24] < (0.24, 0.43] < (0.43, 0.61] < (0.61, 0.8] <
                                           (0.8, 0.99]]

In [ ]:
randomNumbers = np.random.rand(2000)
category3 = pd.qcut(randomNumbers, 4)
category3

[(0.00117, 0.263], (0.771, 1.0], (0.263, 0.504], (0.263, 0.504], (0.263, 0.504], ..., (0.00117, 0.263], (0.771, 1.0], (0.504, 0.771], (0.00117, 0.263], (0.263, 0.504]]
Length: 2000
Categories (4, interval[float64, right]): [(0.00117, 0.263] < (0.263, 0.504] < (0.504, 0.771] <
                                           (0.771, 1.0]]

In [ ]:
pd.value_counts(category3)

/tmp/ipykernel_729/647498483.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(category3)

(0.00117, 0.263]    500
(0.263, 0.504]      500
(0.504, 0.771]      500
(0.771, 1.0]        500
Name: count, dtype: int64

In [ ]:
df=pd.read_csv('/fraudTest.csv')
df.head(10)

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,...,33.9659,-80.9355,333497,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1.371817e+09,33.986391,-81.200714,0.0
1,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,...,40.3207,-110.4360,302,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1.371817e+09,39.450498,-109.960431,0.0
2,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,...,40.6729,-73.5365,34496,"Librarian, public",1970-10-21,c81755dbbbea9d5c77f094348a7579be,1.371817e+09,40.495810,-74.196111,0.0
3,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,28.5697,-80.8191,54767,Set designer,1987-07-25,2159175b9efe66dc301f149d3d5abf8c,1.371817e+09,28.812398,-80.883061,0.0
4,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,44.2529,-85.0170,1126,Furniture designer,1955-07-06,57ff021bd3f328f8738bb535c302a31b,1.371817e+09,44.959148,-85.884734,0.0
5,5,2020-06-21 12:15:37,30407675418785,fraud_Daugherty LLC,kids_pets,19.55,Danielle,Evans,F,76752 David Lodge Apt. 064,...,42.1939,-76.7361,520,Psychotherapist,1991-10-13,798db04aaceb4febd084f1a7c404da93,1.371817e+09,41.747157,-77.584197,0.0
6,6,2020-06-21 12:15:44,213180742685905,fraud_Romaguera Ltd,health_fitness,133.93,Kayla,Sutton,F,010 Weaver Land,...,40.5070,-123.9743,1139,"Therapist, occupational",1951-01-15,17003d7ce534440eadb10c4750e020e5,1.371817e+09,41.499458,-124.888729,0.0
7,7,2020-06-21 12:15:50,3589289942931264,fraud_Reichel LLC,personal_care,10.37,Paula,Estrada,F,350 Stacy Glens,...,43.7557,-97.5936,343,"Development worker, international aid",1972-03-05,8be473af4f05fc6146ea55ace73e7ca2,1.371817e+09,44.495498,-97.728453,0.0
8,8,2020-06-21 12:16:10,3596357274378601,"fraud_Goyette, Howell and Collier",shopping_pos,4.37,David,Everett,M,4138 David Fall,...,41.0001,-78.2357,3688,Advice worker,1973-05-27,71a1da150d1ce510193d7622e08e784e,1.371817e+09,41.546067,-78.120238,0.0
9,9,2020-06-21 12:16:11,3546897637165774,fraud_Kilback Group,food_dining,66.54,Kayla,Obrien,F,7921 Robert Port Suite 343,...,31.6591,-96.8094,263,Barrister,1956-05-30,a7915132c7c4240996ba03a47f81e3bd,1.371817e+09,31.782919,-96.366185,0.0

In [ ]:
TotalTransaction = df["amt"]
TotalTransaction[np.abs(TotalTransaction)>1000]

167       1199.45
428       1881.53
951       3204.98
999       2068.05
1398      1420.90
           ...
157839    2886.52
158014    1153.92
158072    1000.46
158127    1019.77
158895    2111.72
Name: amt, Length: 455, dtype: float64

In [ ]:
df[np.abs(TotalTransaction) > 10000]

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
35542,35542,2020-07-03 18:13:00,4797297220948468262,"fraud_Hagenes, Hermann and Stroman",travel,13149.15,Erica,Briggs,F,3310 Davidson Spurs Apt. 107,...,38.8938,-86.5246,1228,Counsellor,1991-03-13,3a9d71cce25e35776395ce67aefff16f,1.372875e+09,39.435860,-87.298161,0.0
77413,77413,2020-07-18 14:14:57,3501509250702469,fraud_Romaguera and Sons,travel,12882.78,Frank,Anderson,M,0611 Stafford Valley Suite 504,...,26.1184,-81.7361,276002,"Programme researcher, broadcasting/film/video",1979-01-02,7560e4f116a9e89163bbb81881f378ef,1.374157e+09,25.730231,-82.406225,0.0
87794,87794,2020-07-21 13:01:31,3598895972308782,"fraud_Ritchie, Oberbrunner and Cremin",travel,12882.33,Kenneth,Richards,M,994 Livingston Extensions Suite 918,...,41.2403,-82.6078,23805,Copy,1970-02-22,37396c884a1523886312a237254dd241,1.374412e+09,40.424500,-82.475968,0.0

In [ ]:
df=pd.read_csv('/fraudTrain.csv')
df

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1.325376e+09,36.011293,-82.048315,0.0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1.325376e+09,49.159047,-118.186462,0.0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1.325376e+09,43.150704,-112.154481,0.0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1.325376e+09,47.034331,-112.561071,0.0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1.325376e+09,38.674999,-78.632459,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112748,112748,2019-03-04 21:44:03,676195318214,"fraud_Quitzon, Green and Bashirian",shopping_pos,1.94,Brandy,Quinn,F,9734 Beard Fields Suite 885,...,29.6047,-96.5249,106,"Editor, film/video",1983-07-24,1c2ffa4ee1a9f3f2252de5e2d08dd98c,1.330897e+09,29.449723,-97.214296,0.0
112749,112749,2019-03-04 21:44:32,4128027264554082,"fraud_Conroy, Balistreri and Gorczany",health_fitness,28.04,Kyle,Park,M,7507 Larry Passage Suite 859,...,39.8788,-82.1880,1831,Barrister's clerk,1953-10-18,9f16d13daee0b7fbb9c19203f1fb84aa,1.330897e+09,38.899534,-81.457125,0.0
112750,112750,2019-03-04 21:44:53,213153151785052,fraud_Goyette Inc,shopping_net,8.89,Rebecca,Conley,F,181 Moreno Light Apt. 215,...,45.4963,-89.7273,9594,Seismic interpreter,1997-11-23,368f9708c18ca94376a4f108482bb9ae,1.330897e+09,45.896556,-90.575811,0.0
112751,112751,2019-03-04 21:45:08,38588538868506,fraud_Daugherty-Thompson,food_dining,14.68,Jacqueline,Curry,F,3047 Jeff Place,...,30.1886,-103.2214,498,Lexicographer,1990-11-23,acd14b49b0577e152267d30a1769b7c1,1.330898e+09,30.761625,-104.038208,0.0
112752,112752,2019-03-04 21:45:44,4998109455173950,fraud_Pagac LLC,shopping_pos,8.42,Mary,Pruitt,F,2819 Luke Greens Suite 563,...,38.9621,-94.5959,545147,Counsellor,1987-11-18,0,NaN,NaN,NaN,NaN

In [ ]:
df.head(10)

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1.325376e+09,36.011293,-82.048315,0.0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1.325376e+09,49.159047,-118.186462,0.0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1.325376e+09,43.150704,-112.154481,0.0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1.325376e+09,47.034331,-112.561071,0.0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1.325376e+09,38.674999,-78.632459,0.0
5,5,2019-01-01 00:04:08,4767265376804500,"fraud_Stroman, Hudson and Erdman",gas_transport,94.63,Jennifer,Conner,F,4655 David Island,...,40.3750,-75.2045,2158,Transport planner,1961-06-19,189a841a0a8ba03058526bcfe566aab5,1.325376e+09,40.653382,-76.152667,0.0
6,6,2019-01-01 00:04:42,30074693890476,fraud_Rowe-Vandervort,grocery_net,44.54,Kelsey,Richards,F,889 Sarah Station Suite 624,...,37.9931,-100.9893,2691,Arboriculturist,1993-08-16,83ec1cc84142af6e2acf10c44949e720,1.325376e+09,37.162705,-100.153370,0.0
7,7,2019-01-01 00:05:08,6011360759745864,fraud_Corwin-Collins,gas_transport,71.65,Steven,Williams,M,231 Flores Pass Suite 720,...,38.8432,-78.6003,6018,"Designer, multimedia",1947-08-21,6d294ed2cc447d2c71c7171a3d54967c,1.325376e+09,38.948089,-78.540296,0.0
8,8,2019-01-01 00:05:18,4922710831011201,fraud_Herzog Ltd,misc_pos,4.27,Heather,Chase,F,6888 Hicks Stream Suite 954,...,40.3359,-79.6607,1472,Public affairs consultant,1941-03-07,fc28024ce480f8ef21a32d64c93a29f5,1.325376e+09,40.351813,-79.958146,0.0
9,9,2019-01-01 00:06:01,2720830304681674,"fraud_Schoen, Kuphal and Nitzsche",grocery_pos,198.39,Melissa,Aguilar,F,21326 Taylor Squares Suite 708,...,36.5220,-87.3490,151785,Pathologist,1974-03-28,3b9014ea8fb80bd65de0b1463b00b00e,1.325376e+09,37.179198,-87.485381,0.0

In [ ]:
df.tail(10)

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
112743,112743,2019-03-04 21:42:47,3565196229855512,"fraud_O'Connell, Botsford and Hand",home,24.70,Adriana,Harvey,F,715 Joy Prairie,...,40.4815,-92.9951,3805,"Investment banker, corporate",1950-09-15,9272f107077bdc81c1a7b5841b33338b,1.330897e+09,41.349497,-92.709012,0.0
112744,112744,2019-03-04 21:42:49,4377338765909719,fraud_Schoen-Quigley,kids_pets,50.81,Nicholas,Mcmahon,M,2123 Jonathan Falls Suite 753,...,36.1150,-84.0438,4729,"Geologist, wellsite",1982-04-19,bd6a696d043a17ddcbd27cb1afba4335,1.330897e+09,35.398319,-84.201066,0.0
112745,112745,2019-03-04 21:43:16,375848982312810,fraud_Waters-Cruickshank,health_fitness,250.65,Dale,Smith,M,25036 Contreras Turnpike Suite 270,...,31.4841,-97.9903,258,Web designer,1943-12-15,8e9963b0baeb7d920ead666351ac24c9,1.330897e+09,31.879353,-98.461715,0.0
112746,112746,2019-03-04 21:43:39,30238755902988,fraud_Maggio-Fahey,misc_pos,6.77,Danielle,Yu,F,5395 Colon Burgs Suite 037,...,30.5920,-97.2893,1766,Press sub,1976-01-02,0083759dd810a0192a853aaed37e1fc0,1.330897e+09,30.953719,-97.684118,0.0
112747,112747,2019-03-04 21:43:48,375974680629816,fraud_Ebert-Daugherty,travel,5.22,Roberta,Mccarthy,F,94431 Matthew Mall Suite 296,...,41.6611,-73.0449,2376,Herpetologist,1973-04-06,47996ae6d261edec6819bbc302a87973,1.330897e+09,42.143436,-73.780840,0.0
112748,112748,2019-03-04 21:44:03,676195318214,"fraud_Quitzon, Green and Bashirian",shopping_pos,1.94,Brandy,Quinn,F,9734 Beard Fields Suite 885,...,29.6047,-96.5249,106,"Editor, film/video",1983-07-24,1c2ffa4ee1a9f3f2252de5e2d08dd98c,1.330897e+09,29.449723,-97.214296,0.0
112749,112749,2019-03-04 21:44:32,4128027264554082,"fraud_Conroy, Balistreri and Gorczany",health_fitness,28.04,Kyle,Park,M,7507 Larry Passage Suite 859,...,39.8788,-82.1880,1831,Barrister's clerk,1953-10-18,9f16d13daee0b7fbb9c19203f1fb84aa,1.330897e+09,38.899534,-81.457125,0.0
112750,112750,2019-03-04 21:44:53,213153151785052,fraud_Goyette Inc,shopping_net,8.89,Rebecca,Conley,F,181 Moreno Light Apt. 215,...,45.4963,-89.7273,9594,Seismic interpreter,1997-11-23,368f9708c18ca94376a4f108482bb9ae,1.330897e+09,45.896556,-90.575811,0.0
112751,112751,2019-03-04 21:45:08,38588538868506,fraud_Daugherty-Thompson,food_dining,14.68,Jacqueline,Curry,F,3047 Jeff Place,...,30.1886,-103.2214,498,Lexicographer,1990-11-23,acd14b49b0577e152267d30a1769b7c1,1.330898e+09,30.761625,-104.038208,0.0
112752,112752,2019-03-04 21:45:44,4998109455173950,fraud_Pagac LLC,shopping_pos,8.42,Mary,Pruitt,F,2819 Luke Greens Suite 563,...,38.9621,-94.5959,545147,Counsellor,1987-11-18,0,NaN,NaN,NaN,NaN

In [ ]:
Category = df["city_pop"]
Category[np.abs(Category)>100000]

9          151785
12         341043
19         124967
33         378909
34         601723
           ...
112724    2906700
112726     123373
112737     276896
112741     413574
112752     545147
Name: city_pop, Length: 15648, dtype: int64

In [ ]:
TotalTransaction = df["amt"]
TotalTransaction[np.abs(TotalTransaction)>1000]

232       1055.47
511       1636.87
723       1047.52
824       1433.54
1480      1025.38
           ...
111368    1558.65
111525    1408.12
111713    3498.36
112014    1064.13
112422    2229.67
Name: amt, Length: 397, dtype: float64

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler
data={'Age': [25,38,30,37,42,45,35,22,48,21],'Salary': [50000,64000,120000,85000,1200000,600000,85000,1100000,450000,900000]}
df=pd.DataFrame(data)
print("Original Data:\n",df,"\n")

Original Data:
    Age   Salary
0   25    50000
1   38    64000
2   30   120000
3   37    85000
4   42  1200000
5   45   600000
6   35    85000
7   22  1100000
8   48   450000
9   21   900000

In [ ]:
min_max_scaler=MinMaxScaler()
df_min_max=pd.DataFrame(min_max_scaler.fit_transform(df),columns=df.columns)
print("Min-Max Scaled Data:\n",df_min_max,"\n")

Min-Max Scaled Data:
         Age    Salary
0  0.148148  0.000000
1  0.629630  0.012174
2  0.333333  0.060870
3  0.592593  0.030435
4  0.777778  1.000000
5  0.888889  0.478261
6  0.518519  0.030435
7  0.037037  0.913043
8  1.000000  0.347826
9  0.000000  0.739130

In [ ]:
standard_scaler=StandardScaler()
df_standard=pd.DataFrame(standard_scaler.fit_transform(df),columns=df.columns)
print("Standardized Data:\n",df_standard,"\n")

Standardized Data:
         Age    Salary
0 -1.029464 -0.955012
1  0.409572 -0.922826
2 -0.475989 -0.794081
3  0.298877 -0.874546
4  0.852352  1.688859
5  1.184437  0.309448
6  0.077487 -0.874546
7 -1.361549  1.458957
8  1.516523 -0.035405
9 -1.472245  0.999153